name: "godot-ci export"
on: 
  push:
    branches:
      - main

env:
  BUILD_PATH: ./build

jobs:
  export-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: chickensoft-games/setup-godot@v2
        name: Setup Godot
        with:
          version: 4.6.0
      
      - name: Build
        run: |
          mkdir -p $BUILD_PATH
          rm -rf $BUILD_PATH/*
          godot --headless --verbose --export-release "Web" "$BUILD_PATH/index.html"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: web
          path: $BUILD_PATH
